
// Author: DaziZiling

TEXTURE2D(_BaseMap);
TEXTURE2D(_SmoothNoiseMap);
TEXTURE2D(_DetailWaveTexture);
TEXTURE2D(_FluidHeightMap);
TEXTURE2D(_FluidVelocityHeightFoam);
TEXTURE2D(_GroundMap);
TEXTURE2D(_FluxWorldCoastlineMap);
TEXTURE2D(_FluxWorldGroundMap);
TEXTURE2D(_PainterTexture);
TEXTURE2D(_WaveTextureAnimation);
TEXTURE2D(_WaveTextureRenderTarget);
TEXTURE2D(_FluxWaveProfileMap);
SamplerState sampler_FluxWaveProfileMap;
#define _Sampler_FluxWaveProfileMap sampler_FluxWaveProfileMap

TEXTURE2D(_FoamDitherMap);
TEXTURE2D(_FoamNormalSoftHeightMap);
TEXTURE2D(_FoamDistortionMap);

CBUFFER_START(UnityPerMaterial)
int _HideSLW;
int _HideFluxDefaultValue;
float4 _DirectionalLightDirection;
float4 _BaseMap_ST;
float4 _BaseColor;
float4 _WaterScattering;
float4 _WaterAbsorption;
float4 _ColorScaleBehindWater;
float _PhaseG;
float _RefractionIOR;
float _CoastlineFoamDistance;
float _CoastlineFoamScale;
float _CoastlineNormalRange;
float _CoastlineScattringDistance;
float _CoastlineScattringHeight;
float _CoastlineVelocityAdd;
float _CoastlineVelocityScale;
float _NoiseScale;
float _NoiseTime;
float _ShoreWaveScale;
float _ShoreWaveWidth;
int _UsePreciseCoastline;
int _UseDetailWave;
float _DetailWaveChoppiness;
float _DetailWaveHeight;
float _DetailWaveLength;
float _DetailWaveUVOffset;
float _DetailWaveUVSwitching;
float _DetailWaveUVVelocityScale;
int _UseDetailWaveWPO;
float _WaveDetailFastFoam;
float _WaveDetailWPOScale;
float4 _SurfaceAbsorption0;
float4 _SurfaceAbsorption1;
float4 _SurfaceOverlay0;
float4 _SurfaceOverlay1;
float4 _SurfaceScattering0;
float4 _SurfaceScattering1;
float4 _ColorBehind0;
float4 _ColorBehind1;
float4 _ColorBehindShoreline;
float _FoamScatteringScale;
float _PhaseGDeepSunHigh;
float _PhaseGDeepSunLow;
float _PhaseGShallowSunHigh;
float _PhaseGShallowSunLow;
float4 _SurfaceAbsorptionShoreline;
float4 _SurfaceOverlayShoreline;
float _SurfacePhaseG0;
float _SurfacePhaseG1;
float _SurfacePhaseGShoreline;
float4 _SurfaceScatteringShoreline;
float _CaptureHeight;
float _MotionVector;
float4 _SimulationPixelSize;
float4 _StateDecodeData;
float4 _WorldToSimulationUV;
float4 _FluxLevelToWorldGroundUV;
float4 _FluxStateBorders;
float _FluxWorldCoastlineDecode;
float _FluxWorldGroundHeight;
float4 _FluxWorldGroundPixelSize;
int _UseFluxInteraction;
int _UsePainter;
float4 _WorldToPainterUV;
int _StateCheapNormal;
float _StateDistanceDepthMax;
float _StateDistanceDepthOffset;
float _StateDistanceDepthScale;
float _StateDivergenceBase;
float _StateDivergenceIntensity;
float _StateDivergenceMax;
float _StateDivergenceVelocity;
float _StateDivergenceVolumeMin;
float _StateFoamDivergence;
float _StateFoamSlope;
float _StateSteepnessFromHeight;
float _StateSteepnessScale;
float _StateVelocityMax;
float _StateVelocityNormalize;
float _StateVelocityOffsetScale;
float _StateVelocityScale;
float _StateWetHeightOffset;
float _StateWorldPixelSize;
int _UseExtraMasking;
int _UseSection;
float4 _SurfaceCutMask;
int _UseCoastline;
int _UseCutMask;
int _UseOcean;
int _UseSimulation;
int _UseSimulationBlend;
int _UseFluxWaveDistant;
int _UseSingleLayerWater;
int _UseWaveTextureRenderTarget;
float _WaveTextureChoppiness;
float _WaveTextureDecodeHeight;
float _WaveTextureDecodeNormal;
float _WaveTextureDistanceBlend;
float _WaveTextureDivergenceFoam;
float _WaveTextureDivergenceOffset;
float _WaveTextureDivergenceScale;
float _WaveTextureFoamOffset;
float _WaveTextureFoamScale;
float _WaveTextureHeight;
float4 _WaveTextureOffsetScale;
float _WaveTextureOffsetZ;
float _WaveTextureVelocityScaleBottom;
float _WaveTextureVelocityScaleTop;
float _WaveTextureVelocityWind;
float4 _WaveTextureWind;
float4 _FluxWaveProfileDecode;
int _UseFoam;
float _FoamColorDetail;
float _FoamColorAlpha;
float4 _FoamColorBase;
float _FoamNormalBlend;
float _FoamNormalScale;
float _FoamRoughness;
float _FoamSpecular;
float _FoamDitheringAlpha;
float _FoamDitheringOffset;
float _FoamDitheringScale;
float4 _FoamEmissive;
float _FoamHardnessIntensity;
float _FoamHardnessWidth;
float _FoamShallowOffset;
float _FoamShallowScale;
float _FoamSoftBase;
float _FoamSoftIntensity;
float _FoamSoftMax;
float _FoamSoftVelocity;
float _FoamUVAdvectionOffset;
float _FoamUVAdvectionVelocity;
float _FoamUVRandomization;
float _FoamUVScale;
float _FoamUVSpeed;
int _UseFoamDithering;
int _UseFoamDistortion;
float _FoamDistortionIntensity;
float _FoamDistortionScale;
float _FoamDistortionSpeed;
float _CheapScatteringDetails;
float _CheapScatteringPower;
float _CheapScatteringScale;
int _UseCheapScattering;
float4 _CameraRadius;
float _SurfaceOverlayAlpha;
float _WaterDepthUpwardBlend;
float _WaterDitherMasking;
float _WaterDitherSlope;
float _WaterRefractionDistanceOffset;
float _WaterRefractionDistanceScale;
float _WaterRefractionFar;
float _WaterRefractionNear;
float _WaterShallowBlend;
float4 _WaterSpecular;
float _WaterSpecularHorizonDistance;
float _WaterSpecularHorizonOffset;
int _UseWaterRoughnessAdvanced;
float _WaterRoughnessFromFresnel;
float _WaterRoughnessFromSpecular;
float _WaterRoughnessFromSpecularDiv;
float _WaterRoughnessMin;
float _WaveGroundPrediction;
float _WaveProfileAnimationSpeed;
float _WaveProfileDistance;
float _WaveProfileSpeed;
float _WaveProfileWidth;
float _AlphaCutoff;
float4  _DoubleSidedNormalModeConstants;
CBUFFER_END

